# Site Settings
baseurl: ""
url : "https://sohyeonan.github.io"

# Blog Settings
theme_settings :
  title : 블로그
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/smile.png
    username : Sohyeon An
    description : 프론트엔드를 공부하고 있습니다.
    experience :
      - start : 2020-08-30
        end : 2021-06-25
        experience : 위세아이텍, DM사업부 주임
    skills : 
      - skill : HTML5 & CSS
        value : 20  # Percent value
      - skill : JavaScript
        value : 40  # Percent value
      - skill : Java
        value : 70  # Percent value
        
  # Icons
  icons :
    email: ansh4393@gmail.com # Full email address, e.g. "sample@google.com"
    linkedin:  # Full URL 
    github: sohyeonAn # only ID 
    gitlab: 
    bitbucket: 
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname :

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate]
bootstrap:
  assets: true


  # Codepen embed
  codepen_username: ashyeon